# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDeadline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('deadline_type', models.CharField(choices=[('STATUTORY_LIMITATION', 'Statutory Limitation Date'), ('COURT_FILING', 'Court Filing Deadline'), ('WRITTEN_STATEMENT', 'Written Statement / Reply Deadline'), ('COMPLIANCE', 'Court Order Compliance Deadline'), ('APPEAL_PERIOD', 'Limitation for Appeal / Review'), ('DISCOVERY', 'Discovery / Interrogatories Response')], default='COURT_FILING', max_length=30)),
                ('due_date', models.DateField(db_index=True)),
                ('statutory_provision', models.CharField(blank=True, help_text='e.g. Limitation Act Art. 113 or CPC O.VIII R.1', max_length=255, null=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('is_met', models.BooleanField(default=False)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_days_before', models.CharField(default='30,15,7,2,1', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
