# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('DOCUMENTARY', 'Documentary Evidence'), ('ELECTRONIC', 'Electronic / Digital Record'), ('PHYSICAL', 'Physical / Forensic Material'), ('TESTIMONIAL', 'Deposition / Witness Statement')], default='DOCUMENTARY', max_length=30)),
                ('description', models.TextField()),
                ('source_origin', models.CharField(help_text='Where and from whom obtained', max_length=255)),
                ('collection_date', models.DateField()),
                ('custody_location', models.CharField(default='Law Firm Vault', max_length=255)),
                ('admissibility_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('MARKED_EXHIBIT', 'Marked as Exhibit'), ('OBJECTED', 'Objected by Adverse Party'), ('ADMITTED', 'Admitted in Evidence'), ('REJECTED', 'Rejected by Court')], default='SUBMITTED', max_length=30)),
                ('exhibit_mark', models.CharField(blank=True, help_text='e.g. Ex. P-1 or Ex. D-2', max_length=30, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_custodian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_evidence', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChainOfCustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('purpose_of_transfer', models.TextField()),
                ('security_seal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('transferred_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='evidence.evidenceitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WitnessEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('witness_name', models.CharField(max_length=255)),
                ('statement_summary', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_links', to='evidence.evidenceitem')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
