"""
Part 09 for high_courts_corpus
Modular codification slice under 250 KB
"""

HIGH_COURTS_PRECEDENTS_PART_09 = [
    {
        "registry_id": "HC-PREC-0401",
        "citation": "2025 SCC OnLine Del 901",
        "case_name": "Commercial Petitioner 401 v. Industrial Respondent 401",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0402",
        "citation": "2020 SCC OnLine Del 902",
        "case_name": "Commercial Petitioner 402 v. Industrial Respondent 402",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0403",
        "citation": "2021 SCC OnLine Del 903",
        "case_name": "Commercial Petitioner 403 v. Industrial Respondent 403",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0404",
        "citation": "2022 SCC OnLine Del 904",
        "case_name": "Commercial Petitioner 404 v. Industrial Respondent 404",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0405",
        "citation": "2023 SCC OnLine Del 905",
        "case_name": "Commercial Petitioner 405 v. Industrial Respondent 405",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0406",
        "citation": "2024 SCC OnLine Del 906",
        "case_name": "Commercial Petitioner 406 v. Industrial Respondent 406",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0407",
        "citation": "2025 SCC OnLine Del 907",
        "case_name": "Commercial Petitioner 407 v. Industrial Respondent 407",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0408",
        "citation": "2020 SCC OnLine Del 908",
        "case_name": "Commercial Petitioner 408 v. Industrial Respondent 408",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0409",
        "citation": "2021 SCC OnLine Del 909",
        "case_name": "Commercial Petitioner 409 v. Industrial Respondent 409",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0410",
        "citation": "2022 SCC OnLine Del 910",
        "case_name": "Commercial Petitioner 410 v. Industrial Respondent 410",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0411",
        "citation": "2023 SCC OnLine Del 911",
        "case_name": "Commercial Petitioner 411 v. Industrial Respondent 411",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0412",
        "citation": "2024 SCC OnLine Del 912",
        "case_name": "Commercial Petitioner 412 v. Industrial Respondent 412",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0413",
        "citation": "2025 SCC OnLine Del 913",
        "case_name": "Commercial Petitioner 413 v. Industrial Respondent 413",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0414",
        "citation": "2020 SCC OnLine Del 914",
        "case_name": "Commercial Petitioner 414 v. Industrial Respondent 414",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0415",
        "citation": "2021 SCC OnLine Del 915",
        "case_name": "Commercial Petitioner 415 v. Industrial Respondent 415",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0416",
        "citation": "2022 SCC OnLine Del 916",
        "case_name": "Commercial Petitioner 416 v. Industrial Respondent 416",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0417",
        "citation": "2023 SCC OnLine Del 917",
        "case_name": "Commercial Petitioner 417 v. Industrial Respondent 417",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0418",
        "citation": "2024 SCC OnLine Del 918",
        "case_name": "Commercial Petitioner 418 v. Industrial Respondent 418",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0419",
        "citation": "2025 SCC OnLine Del 919",
        "case_name": "Commercial Petitioner 419 v. Industrial Respondent 419",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0420",
        "citation": "2020 SCC OnLine Del 920",
        "case_name": "Commercial Petitioner 420 v. Industrial Respondent 420",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0421",
        "citation": "2021 SCC OnLine Del 921",
        "case_name": "Commercial Petitioner 421 v. Industrial Respondent 421",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0422",
        "citation": "2022 SCC OnLine Del 922",
        "case_name": "Commercial Petitioner 422 v. Industrial Respondent 422",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0423",
        "citation": "2023 SCC OnLine Del 923",
        "case_name": "Commercial Petitioner 423 v. Industrial Respondent 423",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0424",
        "citation": "2024 SCC OnLine Del 924",
        "case_name": "Commercial Petitioner 424 v. Industrial Respondent 424",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0425",
        "citation": "2025 SCC OnLine Del 925",
        "case_name": "Commercial Petitioner 425 v. Industrial Respondent 425",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0426",
        "citation": "2020 SCC OnLine Del 926",
        "case_name": "Commercial Petitioner 426 v. Industrial Respondent 426",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0427",
        "citation": "2021 SCC OnLine Del 927",
        "case_name": "Commercial Petitioner 427 v. Industrial Respondent 427",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0428",
        "citation": "2022 SCC OnLine Del 928",
        "case_name": "Commercial Petitioner 428 v. Industrial Respondent 428",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0429",
        "citation": "2023 SCC OnLine Del 929",
        "case_name": "Commercial Petitioner 429 v. Industrial Respondent 429",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0430",
        "citation": "2024 SCC OnLine Del 930",
        "case_name": "Commercial Petitioner 430 v. Industrial Respondent 430",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0431",
        "citation": "2025 SCC OnLine Del 931",
        "case_name": "Commercial Petitioner 431 v. Industrial Respondent 431",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0432",
        "citation": "2020 SCC OnLine Del 932",
        "case_name": "Commercial Petitioner 432 v. Industrial Respondent 432",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0433",
        "citation": "2021 SCC OnLine Del 933",
        "case_name": "Commercial Petitioner 433 v. Industrial Respondent 433",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0434",
        "citation": "2022 SCC OnLine Del 934",
        "case_name": "Commercial Petitioner 434 v. Industrial Respondent 434",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0435",
        "citation": "2023 SCC OnLine Del 935",
        "case_name": "Commercial Petitioner 435 v. Industrial Respondent 435",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0436",
        "citation": "2024 SCC OnLine Del 936",
        "case_name": "Commercial Petitioner 436 v. Industrial Respondent 436",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0437",
        "citation": "2025 SCC OnLine Del 937",
        "case_name": "Commercial Petitioner 437 v. Industrial Respondent 437",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0438",
        "citation": "2020 SCC OnLine Del 938",
        "case_name": "Commercial Petitioner 438 v. Industrial Respondent 438",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0439",
        "citation": "2021 SCC OnLine Del 939",
        "case_name": "Commercial Petitioner 439 v. Industrial Respondent 439",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0440",
        "citation": "2022 SCC OnLine Del 940",
        "case_name": "Commercial Petitioner 440 v. Industrial Respondent 440",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0441",
        "citation": "2023 SCC OnLine Del 941",
        "case_name": "Commercial Petitioner 441 v. Industrial Respondent 441",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0442",
        "citation": "2024 SCC OnLine Del 942",
        "case_name": "Commercial Petitioner 442 v. Industrial Respondent 442",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0443",
        "citation": "2025 SCC OnLine Del 943",
        "case_name": "Commercial Petitioner 443 v. Industrial Respondent 443",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0444",
        "citation": "2020 SCC OnLine Del 944",
        "case_name": "Commercial Petitioner 444 v. Industrial Respondent 444",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0445",
        "citation": "2021 SCC OnLine Del 945",
        "case_name": "Commercial Petitioner 445 v. Industrial Respondent 445",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0446",
        "citation": "2022 SCC OnLine Del 946",
        "case_name": "Commercial Petitioner 446 v. Industrial Respondent 446",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0447",
        "citation": "2023 SCC OnLine Del 947",
        "case_name": "Commercial Petitioner 447 v. Industrial Respondent 447",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0448",
        "citation": "2024 SCC OnLine Del 948",
        "case_name": "Commercial Petitioner 448 v. Industrial Respondent 448",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0449",
        "citation": "2025 SCC OnLine Del 949",
        "case_name": "Commercial Petitioner 449 v. Industrial Respondent 449",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0450",
        "citation": "2020 SCC OnLine Del 950",
        "case_name": "Commercial Petitioner 450 v. Industrial Respondent 450",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
]
