"""
Part 08 for high_courts_corpus
Modular codification slice under 250 KB
"""

HIGH_COURTS_PRECEDENTS_PART_08 = [
    {
        "registry_id": "HC-PREC-0351",
        "citation": "2023 SCC OnLine Del 851",
        "case_name": "Commercial Petitioner 351 v. Industrial Respondent 351",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0352",
        "citation": "2024 SCC OnLine Del 852",
        "case_name": "Commercial Petitioner 352 v. Industrial Respondent 352",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0353",
        "citation": "2025 SCC OnLine Del 853",
        "case_name": "Commercial Petitioner 353 v. Industrial Respondent 353",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0354",
        "citation": "2020 SCC OnLine Del 854",
        "case_name": "Commercial Petitioner 354 v. Industrial Respondent 354",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0355",
        "citation": "2021 SCC OnLine Del 855",
        "case_name": "Commercial Petitioner 355 v. Industrial Respondent 355",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0356",
        "citation": "2022 SCC OnLine Del 856",
        "case_name": "Commercial Petitioner 356 v. Industrial Respondent 356",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0357",
        "citation": "2023 SCC OnLine Del 857",
        "case_name": "Commercial Petitioner 357 v. Industrial Respondent 357",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0358",
        "citation": "2024 SCC OnLine Del 858",
        "case_name": "Commercial Petitioner 358 v. Industrial Respondent 358",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0359",
        "citation": "2025 SCC OnLine Del 859",
        "case_name": "Commercial Petitioner 359 v. Industrial Respondent 359",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0360",
        "citation": "2020 SCC OnLine Del 860",
        "case_name": "Commercial Petitioner 360 v. Industrial Respondent 360",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0361",
        "citation": "2021 SCC OnLine Del 861",
        "case_name": "Commercial Petitioner 361 v. Industrial Respondent 361",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0362",
        "citation": "2022 SCC OnLine Del 862",
        "case_name": "Commercial Petitioner 362 v. Industrial Respondent 362",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0363",
        "citation": "2023 SCC OnLine Del 863",
        "case_name": "Commercial Petitioner 363 v. Industrial Respondent 363",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0364",
        "citation": "2024 SCC OnLine Del 864",
        "case_name": "Commercial Petitioner 364 v. Industrial Respondent 364",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0365",
        "citation": "2025 SCC OnLine Del 865",
        "case_name": "Commercial Petitioner 365 v. Industrial Respondent 365",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0366",
        "citation": "2020 SCC OnLine Del 866",
        "case_name": "Commercial Petitioner 366 v. Industrial Respondent 366",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0367",
        "citation": "2021 SCC OnLine Del 867",
        "case_name": "Commercial Petitioner 367 v. Industrial Respondent 367",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0368",
        "citation": "2022 SCC OnLine Del 868",
        "case_name": "Commercial Petitioner 368 v. Industrial Respondent 368",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0369",
        "citation": "2023 SCC OnLine Del 869",
        "case_name": "Commercial Petitioner 369 v. Industrial Respondent 369",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0370",
        "citation": "2024 SCC OnLine Del 870",
        "case_name": "Commercial Petitioner 370 v. Industrial Respondent 370",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0371",
        "citation": "2025 SCC OnLine Del 871",
        "case_name": "Commercial Petitioner 371 v. Industrial Respondent 371",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0372",
        "citation": "2020 SCC OnLine Del 872",
        "case_name": "Commercial Petitioner 372 v. Industrial Respondent 372",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0373",
        "citation": "2021 SCC OnLine Del 873",
        "case_name": "Commercial Petitioner 373 v. Industrial Respondent 373",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0374",
        "citation": "2022 SCC OnLine Del 874",
        "case_name": "Commercial Petitioner 374 v. Industrial Respondent 374",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0375",
        "citation": "2023 SCC OnLine Del 875",
        "case_name": "Commercial Petitioner 375 v. Industrial Respondent 375",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0376",
        "citation": "2024 SCC OnLine Del 876",
        "case_name": "Commercial Petitioner 376 v. Industrial Respondent 376",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0377",
        "citation": "2025 SCC OnLine Del 877",
        "case_name": "Commercial Petitioner 377 v. Industrial Respondent 377",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0378",
        "citation": "2020 SCC OnLine Del 878",
        "case_name": "Commercial Petitioner 378 v. Industrial Respondent 378",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0379",
        "citation": "2021 SCC OnLine Del 879",
        "case_name": "Commercial Petitioner 379 v. Industrial Respondent 379",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0380",
        "citation": "2022 SCC OnLine Del 880",
        "case_name": "Commercial Petitioner 380 v. Industrial Respondent 380",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0381",
        "citation": "2023 SCC OnLine Del 881",
        "case_name": "Commercial Petitioner 381 v. Industrial Respondent 381",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0382",
        "citation": "2024 SCC OnLine Del 882",
        "case_name": "Commercial Petitioner 382 v. Industrial Respondent 382",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0383",
        "citation": "2025 SCC OnLine Del 883",
        "case_name": "Commercial Petitioner 383 v. Industrial Respondent 383",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0384",
        "citation": "2020 SCC OnLine Del 884",
        "case_name": "Commercial Petitioner 384 v. Industrial Respondent 384",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0385",
        "citation": "2021 SCC OnLine Del 885",
        "case_name": "Commercial Petitioner 385 v. Industrial Respondent 385",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0386",
        "citation": "2022 SCC OnLine Del 886",
        "case_name": "Commercial Petitioner 386 v. Industrial Respondent 386",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0387",
        "citation": "2023 SCC OnLine Del 887",
        "case_name": "Commercial Petitioner 387 v. Industrial Respondent 387",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0388",
        "citation": "2024 SCC OnLine Del 888",
        "case_name": "Commercial Petitioner 388 v. Industrial Respondent 388",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0389",
        "citation": "2025 SCC OnLine Del 889",
        "case_name": "Commercial Petitioner 389 v. Industrial Respondent 389",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0390",
        "citation": "2020 SCC OnLine Del 890",
        "case_name": "Commercial Petitioner 390 v. Industrial Respondent 390",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0391",
        "citation": "2021 SCC OnLine Del 891",
        "case_name": "Commercial Petitioner 391 v. Industrial Respondent 391",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0392",
        "citation": "2022 SCC OnLine Del 892",
        "case_name": "Commercial Petitioner 392 v. Industrial Respondent 392",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0393",
        "citation": "2023 SCC OnLine Del 893",
        "case_name": "Commercial Petitioner 393 v. Industrial Respondent 393",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0394",
        "citation": "2024 SCC OnLine Del 894",
        "case_name": "Commercial Petitioner 394 v. Industrial Respondent 394",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0395",
        "citation": "2025 SCC OnLine Del 895",
        "case_name": "Commercial Petitioner 395 v. Industrial Respondent 395",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0396",
        "citation": "2020 SCC OnLine Del 896",
        "case_name": "Commercial Petitioner 396 v. Industrial Respondent 396",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0397",
        "citation": "2021 SCC OnLine Del 897",
        "case_name": "Commercial Petitioner 397 v. Industrial Respondent 397",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0398",
        "citation": "2022 SCC OnLine Del 898",
        "case_name": "Commercial Petitioner 398 v. Industrial Respondent 398",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0399",
        "citation": "2023 SCC OnLine Del 899",
        "case_name": "Commercial Petitioner 399 v. Industrial Respondent 399",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0400",
        "citation": "2024 SCC OnLine Del 900",
        "case_name": "Commercial Petitioner 400 v. Industrial Respondent 400",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
]
