"""
Part 06 for high_courts_corpus
Modular codification slice under 250 KB
"""

HIGH_COURTS_PRECEDENTS_PART_06 = [
    {
        "registry_id": "HC-PREC-0251",
        "citation": "2025 SCC OnLine Del 751",
        "case_name": "Commercial Petitioner 251 v. Industrial Respondent 251",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0252",
        "citation": "2020 SCC OnLine Del 752",
        "case_name": "Commercial Petitioner 252 v. Industrial Respondent 252",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0253",
        "citation": "2021 SCC OnLine Del 753",
        "case_name": "Commercial Petitioner 253 v. Industrial Respondent 253",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0254",
        "citation": "2022 SCC OnLine Del 754",
        "case_name": "Commercial Petitioner 254 v. Industrial Respondent 254",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0255",
        "citation": "2023 SCC OnLine Del 755",
        "case_name": "Commercial Petitioner 255 v. Industrial Respondent 255",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0256",
        "citation": "2024 SCC OnLine Del 756",
        "case_name": "Commercial Petitioner 256 v. Industrial Respondent 256",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0257",
        "citation": "2025 SCC OnLine Del 757",
        "case_name": "Commercial Petitioner 257 v. Industrial Respondent 257",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0258",
        "citation": "2020 SCC OnLine Del 758",
        "case_name": "Commercial Petitioner 258 v. Industrial Respondent 258",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0259",
        "citation": "2021 SCC OnLine Del 759",
        "case_name": "Commercial Petitioner 259 v. Industrial Respondent 259",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0260",
        "citation": "2022 SCC OnLine Del 760",
        "case_name": "Commercial Petitioner 260 v. Industrial Respondent 260",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0261",
        "citation": "2023 SCC OnLine Del 761",
        "case_name": "Commercial Petitioner 261 v. Industrial Respondent 261",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0262",
        "citation": "2024 SCC OnLine Del 762",
        "case_name": "Commercial Petitioner 262 v. Industrial Respondent 262",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0263",
        "citation": "2025 SCC OnLine Del 763",
        "case_name": "Commercial Petitioner 263 v. Industrial Respondent 263",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0264",
        "citation": "2020 SCC OnLine Del 764",
        "case_name": "Commercial Petitioner 264 v. Industrial Respondent 264",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0265",
        "citation": "2021 SCC OnLine Del 765",
        "case_name": "Commercial Petitioner 265 v. Industrial Respondent 265",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0266",
        "citation": "2022 SCC OnLine Del 766",
        "case_name": "Commercial Petitioner 266 v. Industrial Respondent 266",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0267",
        "citation": "2023 SCC OnLine Del 767",
        "case_name": "Commercial Petitioner 267 v. Industrial Respondent 267",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0268",
        "citation": "2024 SCC OnLine Del 768",
        "case_name": "Commercial Petitioner 268 v. Industrial Respondent 268",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0269",
        "citation": "2025 SCC OnLine Del 769",
        "case_name": "Commercial Petitioner 269 v. Industrial Respondent 269",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0270",
        "citation": "2020 SCC OnLine Del 770",
        "case_name": "Commercial Petitioner 270 v. Industrial Respondent 270",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0271",
        "citation": "2021 SCC OnLine Del 771",
        "case_name": "Commercial Petitioner 271 v. Industrial Respondent 271",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0272",
        "citation": "2022 SCC OnLine Del 772",
        "case_name": "Commercial Petitioner 272 v. Industrial Respondent 272",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0273",
        "citation": "2023 SCC OnLine Del 773",
        "case_name": "Commercial Petitioner 273 v. Industrial Respondent 273",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0274",
        "citation": "2024 SCC OnLine Del 774",
        "case_name": "Commercial Petitioner 274 v. Industrial Respondent 274",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0275",
        "citation": "2025 SCC OnLine Del 775",
        "case_name": "Commercial Petitioner 275 v. Industrial Respondent 275",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0276",
        "citation": "2020 SCC OnLine Del 776",
        "case_name": "Commercial Petitioner 276 v. Industrial Respondent 276",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0277",
        "citation": "2021 SCC OnLine Del 777",
        "case_name": "Commercial Petitioner 277 v. Industrial Respondent 277",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0278",
        "citation": "2022 SCC OnLine Del 778",
        "case_name": "Commercial Petitioner 278 v. Industrial Respondent 278",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0279",
        "citation": "2023 SCC OnLine Del 779",
        "case_name": "Commercial Petitioner 279 v. Industrial Respondent 279",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0280",
        "citation": "2024 SCC OnLine Del 780",
        "case_name": "Commercial Petitioner 280 v. Industrial Respondent 280",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0281",
        "citation": "2025 SCC OnLine Del 781",
        "case_name": "Commercial Petitioner 281 v. Industrial Respondent 281",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0282",
        "citation": "2020 SCC OnLine Del 782",
        "case_name": "Commercial Petitioner 282 v. Industrial Respondent 282",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0283",
        "citation": "2021 SCC OnLine Del 783",
        "case_name": "Commercial Petitioner 283 v. Industrial Respondent 283",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0284",
        "citation": "2022 SCC OnLine Del 784",
        "case_name": "Commercial Petitioner 284 v. Industrial Respondent 284",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0285",
        "citation": "2023 SCC OnLine Del 785",
        "case_name": "Commercial Petitioner 285 v. Industrial Respondent 285",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0286",
        "citation": "2024 SCC OnLine Del 786",
        "case_name": "Commercial Petitioner 286 v. Industrial Respondent 286",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0287",
        "citation": "2025 SCC OnLine Del 787",
        "case_name": "Commercial Petitioner 287 v. Industrial Respondent 287",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0288",
        "citation": "2020 SCC OnLine Del 788",
        "case_name": "Commercial Petitioner 288 v. Industrial Respondent 288",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0289",
        "citation": "2021 SCC OnLine Del 789",
        "case_name": "Commercial Petitioner 289 v. Industrial Respondent 289",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0290",
        "citation": "2022 SCC OnLine Del 790",
        "case_name": "Commercial Petitioner 290 v. Industrial Respondent 290",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0291",
        "citation": "2023 SCC OnLine Del 791",
        "case_name": "Commercial Petitioner 291 v. Industrial Respondent 291",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0292",
        "citation": "2024 SCC OnLine Del 792",
        "case_name": "Commercial Petitioner 292 v. Industrial Respondent 292",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0293",
        "citation": "2025 SCC OnLine Del 793",
        "case_name": "Commercial Petitioner 293 v. Industrial Respondent 293",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0294",
        "citation": "2020 SCC OnLine Del 794",
        "case_name": "Commercial Petitioner 294 v. Industrial Respondent 294",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0295",
        "citation": "2021 SCC OnLine Del 795",
        "case_name": "Commercial Petitioner 295 v. Industrial Respondent 295",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0296",
        "citation": "2022 SCC OnLine Del 796",
        "case_name": "Commercial Petitioner 296 v. Industrial Respondent 296",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0297",
        "citation": "2023 SCC OnLine Del 797",
        "case_name": "Commercial Petitioner 297 v. Industrial Respondent 297",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0298",
        "citation": "2024 SCC OnLine Del 798",
        "case_name": "Commercial Petitioner 298 v. Industrial Respondent 298",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0299",
        "citation": "2025 SCC OnLine Del 799",
        "case_name": "Commercial Petitioner 299 v. Industrial Respondent 299",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0300",
        "citation": "2020 SCC OnLine Del 800",
        "case_name": "Commercial Petitioner 300 v. Industrial Respondent 300",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
]
