"""
Part 10 for high_courts_corpus
Modular codification slice under 250 KB
"""

HIGH_COURTS_PRECEDENTS_PART_10 = [
    {
        "registry_id": "HC-PREC-0451",
        "citation": "2021 SCC OnLine Del 951",
        "case_name": "Commercial Petitioner 451 v. Industrial Respondent 451",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0452",
        "citation": "2022 SCC OnLine Del 952",
        "case_name": "Commercial Petitioner 452 v. Industrial Respondent 452",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0453",
        "citation": "2023 SCC OnLine Del 953",
        "case_name": "Commercial Petitioner 453 v. Industrial Respondent 453",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0454",
        "citation": "2024 SCC OnLine Del 954",
        "case_name": "Commercial Petitioner 454 v. Industrial Respondent 454",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0455",
        "citation": "2025 SCC OnLine Del 955",
        "case_name": "Commercial Petitioner 455 v. Industrial Respondent 455",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0456",
        "citation": "2020 SCC OnLine Del 956",
        "case_name": "Commercial Petitioner 456 v. Industrial Respondent 456",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0457",
        "citation": "2021 SCC OnLine Del 957",
        "case_name": "Commercial Petitioner 457 v. Industrial Respondent 457",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0458",
        "citation": "2022 SCC OnLine Del 958",
        "case_name": "Commercial Petitioner 458 v. Industrial Respondent 458",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0459",
        "citation": "2023 SCC OnLine Del 959",
        "case_name": "Commercial Petitioner 459 v. Industrial Respondent 459",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0460",
        "citation": "2024 SCC OnLine Del 960",
        "case_name": "Commercial Petitioner 460 v. Industrial Respondent 460",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0461",
        "citation": "2025 SCC OnLine Del 961",
        "case_name": "Commercial Petitioner 461 v. Industrial Respondent 461",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0462",
        "citation": "2020 SCC OnLine Del 962",
        "case_name": "Commercial Petitioner 462 v. Industrial Respondent 462",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0463",
        "citation": "2021 SCC OnLine Del 963",
        "case_name": "Commercial Petitioner 463 v. Industrial Respondent 463",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0464",
        "citation": "2022 SCC OnLine Del 964",
        "case_name": "Commercial Petitioner 464 v. Industrial Respondent 464",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0465",
        "citation": "2023 SCC OnLine Del 965",
        "case_name": "Commercial Petitioner 465 v. Industrial Respondent 465",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0466",
        "citation": "2024 SCC OnLine Del 966",
        "case_name": "Commercial Petitioner 466 v. Industrial Respondent 466",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0467",
        "citation": "2025 SCC OnLine Del 967",
        "case_name": "Commercial Petitioner 467 v. Industrial Respondent 467",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0468",
        "citation": "2020 SCC OnLine Del 968",
        "case_name": "Commercial Petitioner 468 v. Industrial Respondent 468",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0469",
        "citation": "2021 SCC OnLine Del 969",
        "case_name": "Commercial Petitioner 469 v. Industrial Respondent 469",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0470",
        "citation": "2022 SCC OnLine Del 970",
        "case_name": "Commercial Petitioner 470 v. Industrial Respondent 470",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0471",
        "citation": "2023 SCC OnLine Del 971",
        "case_name": "Commercial Petitioner 471 v. Industrial Respondent 471",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0472",
        "citation": "2024 SCC OnLine Del 972",
        "case_name": "Commercial Petitioner 472 v. Industrial Respondent 472",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0473",
        "citation": "2025 SCC OnLine Del 973",
        "case_name": "Commercial Petitioner 473 v. Industrial Respondent 473",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0474",
        "citation": "2020 SCC OnLine Del 974",
        "case_name": "Commercial Petitioner 474 v. Industrial Respondent 474",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0475",
        "citation": "2021 SCC OnLine Del 975",
        "case_name": "Commercial Petitioner 475 v. Industrial Respondent 475",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0476",
        "citation": "2022 SCC OnLine Del 976",
        "case_name": "Commercial Petitioner 476 v. Industrial Respondent 476",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0477",
        "citation": "2023 SCC OnLine Del 977",
        "case_name": "Commercial Petitioner 477 v. Industrial Respondent 477",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0478",
        "citation": "2024 SCC OnLine Del 978",
        "case_name": "Commercial Petitioner 478 v. Industrial Respondent 478",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0479",
        "citation": "2025 SCC OnLine Del 979",
        "case_name": "Commercial Petitioner 479 v. Industrial Respondent 479",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0480",
        "citation": "2020 SCC OnLine Del 980",
        "case_name": "Commercial Petitioner 480 v. Industrial Respondent 480",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0481",
        "citation": "2021 SCC OnLine Del 981",
        "case_name": "Commercial Petitioner 481 v. Industrial Respondent 481",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0482",
        "citation": "2022 SCC OnLine Del 982",
        "case_name": "Commercial Petitioner 482 v. Industrial Respondent 482",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0483",
        "citation": "2023 SCC OnLine Del 983",
        "case_name": "Commercial Petitioner 483 v. Industrial Respondent 483",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0484",
        "citation": "2024 SCC OnLine Del 984",
        "case_name": "Commercial Petitioner 484 v. Industrial Respondent 484",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0485",
        "citation": "2025 SCC OnLine Del 985",
        "case_name": "Commercial Petitioner 485 v. Industrial Respondent 485",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0486",
        "citation": "2020 SCC OnLine Del 986",
        "case_name": "Commercial Petitioner 486 v. Industrial Respondent 486",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0487",
        "citation": "2021 SCC OnLine Del 987",
        "case_name": "Commercial Petitioner 487 v. Industrial Respondent 487",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0488",
        "citation": "2022 SCC OnLine Del 988",
        "case_name": "Commercial Petitioner 488 v. Industrial Respondent 488",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0489",
        "citation": "2023 SCC OnLine Del 989",
        "case_name": "Commercial Petitioner 489 v. Industrial Respondent 489",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0490",
        "citation": "2024 SCC OnLine Del 990",
        "case_name": "Commercial Petitioner 490 v. Industrial Respondent 490",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0491",
        "citation": "2025 SCC OnLine Del 991",
        "case_name": "Commercial Petitioner 491 v. Industrial Respondent 491",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0492",
        "citation": "2020 SCC OnLine Del 992",
        "case_name": "Commercial Petitioner 492 v. Industrial Respondent 492",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0493",
        "citation": "2021 SCC OnLine Del 993",
        "case_name": "Commercial Petitioner 493 v. Industrial Respondent 493",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0494",
        "citation": "2022 SCC OnLine Del 994",
        "case_name": "Commercial Petitioner 494 v. Industrial Respondent 494",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0495",
        "citation": "2023 SCC OnLine Del 995",
        "case_name": "Commercial Petitioner 495 v. Industrial Respondent 495",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0496",
        "citation": "2024 SCC OnLine Del 996",
        "case_name": "Commercial Petitioner 496 v. Industrial Respondent 496",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0497",
        "citation": "2025 SCC OnLine Del 997",
        "case_name": "Commercial Petitioner 497 v. Industrial Respondent 497",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0498",
        "citation": "2020 SCC OnLine Del 998",
        "case_name": "Commercial Petitioner 498 v. Industrial Respondent 498",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0499",
        "citation": "2021 SCC OnLine Del 999",
        "case_name": "Commercial Petitioner 499 v. Industrial Respondent 499",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0500",
        "citation": "2022 SCC OnLine Del 1000",
        "case_name": "Commercial Petitioner 500 v. Industrial Respondent 500",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
]
