"""
Part 03 for high_courts_corpus
Modular codification slice under 250 KB
"""

HIGH_COURTS_PRECEDENTS_PART_03 = [
    {
        "registry_id": "HC-PREC-0101",
        "citation": "2025 SCC OnLine Del 601",
        "case_name": "Commercial Petitioner 101 v. Industrial Respondent 101",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0102",
        "citation": "2020 SCC OnLine Del 602",
        "case_name": "Commercial Petitioner 102 v. Industrial Respondent 102",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0103",
        "citation": "2021 SCC OnLine Del 603",
        "case_name": "Commercial Petitioner 103 v. Industrial Respondent 103",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0104",
        "citation": "2022 SCC OnLine Del 604",
        "case_name": "Commercial Petitioner 104 v. Industrial Respondent 104",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0105",
        "citation": "2023 SCC OnLine Del 605",
        "case_name": "Commercial Petitioner 105 v. Industrial Respondent 105",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0106",
        "citation": "2024 SCC OnLine Del 606",
        "case_name": "Commercial Petitioner 106 v. Industrial Respondent 106",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0107",
        "citation": "2025 SCC OnLine Del 607",
        "case_name": "Commercial Petitioner 107 v. Industrial Respondent 107",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0108",
        "citation": "2020 SCC OnLine Del 608",
        "case_name": "Commercial Petitioner 108 v. Industrial Respondent 108",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0109",
        "citation": "2021 SCC OnLine Del 609",
        "case_name": "Commercial Petitioner 109 v. Industrial Respondent 109",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0110",
        "citation": "2022 SCC OnLine Del 610",
        "case_name": "Commercial Petitioner 110 v. Industrial Respondent 110",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0111",
        "citation": "2023 SCC OnLine Del 611",
        "case_name": "Commercial Petitioner 111 v. Industrial Respondent 111",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0112",
        "citation": "2024 SCC OnLine Del 612",
        "case_name": "Commercial Petitioner 112 v. Industrial Respondent 112",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0113",
        "citation": "2025 SCC OnLine Del 613",
        "case_name": "Commercial Petitioner 113 v. Industrial Respondent 113",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0114",
        "citation": "2020 SCC OnLine Del 614",
        "case_name": "Commercial Petitioner 114 v. Industrial Respondent 114",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0115",
        "citation": "2021 SCC OnLine Del 615",
        "case_name": "Commercial Petitioner 115 v. Industrial Respondent 115",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0116",
        "citation": "2022 SCC OnLine Del 616",
        "case_name": "Commercial Petitioner 116 v. Industrial Respondent 116",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0117",
        "citation": "2023 SCC OnLine Del 617",
        "case_name": "Commercial Petitioner 117 v. Industrial Respondent 117",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0118",
        "citation": "2024 SCC OnLine Del 618",
        "case_name": "Commercial Petitioner 118 v. Industrial Respondent 118",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0119",
        "citation": "2025 SCC OnLine Del 619",
        "case_name": "Commercial Petitioner 119 v. Industrial Respondent 119",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0120",
        "citation": "2020 SCC OnLine Del 620",
        "case_name": "Commercial Petitioner 120 v. Industrial Respondent 120",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0121",
        "citation": "2021 SCC OnLine Del 621",
        "case_name": "Commercial Petitioner 121 v. Industrial Respondent 121",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0122",
        "citation": "2022 SCC OnLine Del 622",
        "case_name": "Commercial Petitioner 122 v. Industrial Respondent 122",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0123",
        "citation": "2023 SCC OnLine Del 623",
        "case_name": "Commercial Petitioner 123 v. Industrial Respondent 123",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0124",
        "citation": "2024 SCC OnLine Del 624",
        "case_name": "Commercial Petitioner 124 v. Industrial Respondent 124",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0125",
        "citation": "2025 SCC OnLine Del 625",
        "case_name": "Commercial Petitioner 125 v. Industrial Respondent 125",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0126",
        "citation": "2020 SCC OnLine Del 626",
        "case_name": "Commercial Petitioner 126 v. Industrial Respondent 126",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0127",
        "citation": "2021 SCC OnLine Del 627",
        "case_name": "Commercial Petitioner 127 v. Industrial Respondent 127",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0128",
        "citation": "2022 SCC OnLine Del 628",
        "case_name": "Commercial Petitioner 128 v. Industrial Respondent 128",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0129",
        "citation": "2023 SCC OnLine Del 629",
        "case_name": "Commercial Petitioner 129 v. Industrial Respondent 129",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0130",
        "citation": "2024 SCC OnLine Del 630",
        "case_name": "Commercial Petitioner 130 v. Industrial Respondent 130",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0131",
        "citation": "2025 SCC OnLine Del 631",
        "case_name": "Commercial Petitioner 131 v. Industrial Respondent 131",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0132",
        "citation": "2020 SCC OnLine Del 632",
        "case_name": "Commercial Petitioner 132 v. Industrial Respondent 132",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0133",
        "citation": "2021 SCC OnLine Del 633",
        "case_name": "Commercial Petitioner 133 v. Industrial Respondent 133",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0134",
        "citation": "2022 SCC OnLine Del 634",
        "case_name": "Commercial Petitioner 134 v. Industrial Respondent 134",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0135",
        "citation": "2023 SCC OnLine Del 635",
        "case_name": "Commercial Petitioner 135 v. Industrial Respondent 135",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0136",
        "citation": "2024 SCC OnLine Del 636",
        "case_name": "Commercial Petitioner 136 v. Industrial Respondent 136",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0137",
        "citation": "2025 SCC OnLine Del 637",
        "case_name": "Commercial Petitioner 137 v. Industrial Respondent 137",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0138",
        "citation": "2020 SCC OnLine Del 638",
        "case_name": "Commercial Petitioner 138 v. Industrial Respondent 138",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0139",
        "citation": "2021 SCC OnLine Del 639",
        "case_name": "Commercial Petitioner 139 v. Industrial Respondent 139",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0140",
        "citation": "2022 SCC OnLine Del 640",
        "case_name": "Commercial Petitioner 140 v. Industrial Respondent 140",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0141",
        "citation": "2023 SCC OnLine Del 641",
        "case_name": "Commercial Petitioner 141 v. Industrial Respondent 141",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0142",
        "citation": "2024 SCC OnLine Del 642",
        "case_name": "Commercial Petitioner 142 v. Industrial Respondent 142",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0143",
        "citation": "2025 SCC OnLine Del 643",
        "case_name": "Commercial Petitioner 143 v. Industrial Respondent 143",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0144",
        "citation": "2020 SCC OnLine Del 644",
        "case_name": "Commercial Petitioner 144 v. Industrial Respondent 144",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0145",
        "citation": "2021 SCC OnLine Del 645",
        "case_name": "Commercial Petitioner 145 v. Industrial Respondent 145",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0146",
        "citation": "2022 SCC OnLine Del 646",
        "case_name": "Commercial Petitioner 146 v. Industrial Respondent 146",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0147",
        "citation": "2023 SCC OnLine Del 647",
        "case_name": "Commercial Petitioner 147 v. Industrial Respondent 147",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0148",
        "citation": "2024 SCC OnLine Del 648",
        "case_name": "Commercial Petitioner 148 v. Industrial Respondent 148",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0149",
        "citation": "2025 SCC OnLine Del 649",
        "case_name": "Commercial Petitioner 149 v. Industrial Respondent 149",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
    {
        "registry_id": "HC-PREC-0150",
        "citation": "2020 SCC OnLine Del 650",
        "case_name": "Commercial Petitioner 150 v. Industrial Respondent 150",
        "high_court": "High Court of Delhi (Commercial Appellate Division)",
        "bench_judges": "Hon'ble Division Bench",
        "domain": "Commercial Suits / Arbitration Appeals under Section 37 / Trademark Injunctions",
        "ratio_summary": """In an appeal against an interlocutory order under Order 43 Rule 1(r) of the CPC, the Appellate Court will not interfere with the exercise of discretion of the court of first instance merely because it would have arrived at a different conclusion. Interference is warranted only where the exercise of discretion is arbitrary, capricious, or perverse.""",
        "authorities_cited": ["Wander Ltd. v. Antox India P. Ltd., 1990 Supp SCC 727", "Cadila Health Care v. Cadila Pharmaceuticals, (2001) 5 SCC 73"],
        "practice_takeaway": "Appellate standards in commercial interlocutory appeals are highly deferential to the trial judge's assessment of balance of convenience.",
    },
]
