"""
supreme_court_corpus - Aggregator Module
Preserves backward compatibility while keeping all underlying files < 250 KB
"""

from .supreme_court_corpus_part01 import SUPREME_COURT_PRECEDENTS_PART_01
from .supreme_court_corpus_part02 import SUPREME_COURT_PRECEDENTS_PART_02
from .supreme_court_corpus_part03 import SUPREME_COURT_PRECEDENTS_PART_03
from .supreme_court_corpus_part04 import SUPREME_COURT_PRECEDENTS_PART_04
from .supreme_court_corpus_part05 import SUPREME_COURT_PRECEDENTS_PART_05
from .supreme_court_corpus_part06 import SUPREME_COURT_PRECEDENTS_PART_06
from .supreme_court_corpus_part07 import SUPREME_COURT_PRECEDENTS_PART_07
from .supreme_court_corpus_part08 import SUPREME_COURT_PRECEDENTS_PART_08
from .supreme_court_corpus_part09 import SUPREME_COURT_PRECEDENTS_PART_09
from .supreme_court_corpus_part10 import SUPREME_COURT_PRECEDENTS_PART_10
from .supreme_court_corpus_part11 import SUPREME_COURT_PRECEDENTS_PART_11
from .supreme_court_corpus_part12 import SUPREME_COURT_PRECEDENTS_PART_12

SUPREME_COURT_PRECEDENTS = SUPREME_COURT_PRECEDENTS_PART_01 + SUPREME_COURT_PRECEDENTS_PART_02 + SUPREME_COURT_PRECEDENTS_PART_03 + SUPREME_COURT_PRECEDENTS_PART_04 + SUPREME_COURT_PRECEDENTS_PART_05 + SUPREME_COURT_PRECEDENTS_PART_06 + SUPREME_COURT_PRECEDENTS_PART_07 + SUPREME_COURT_PRECEDENTS_PART_08 + SUPREME_COURT_PRECEDENTS_PART_09 + SUPREME_COURT_PRECEDENTS_PART_10 + SUPREME_COURT_PRECEDENTS_PART_11 + SUPREME_COURT_PRECEDENTS_PART_12

