# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('courts', '0001_initial'),
        ('hearings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('INTERIM', 'Interim Order / Injunction'), ('PROCEDURAL', 'Procedural Direction'), ('CONSENT', 'Consent Order'), ('FINAL_JUDGMENT', 'Final Judgment & Decree'), ('DISMISSAL', 'Order of Dismissal')], default='INTERIM', max_length=30)),
                ('order_date', models.DateField(db_index=True)),
                ('summary', models.TextField()),
                ('operative_directions', models.TextField()),
                ('certified_copy', models.FileField(blank=True, null=True, upload_to='court_orders/%Y/%m/')),
                ('requires_compliance', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_orders', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hearings.hearing')),
                ('presiding_judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.judge')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction_text', models.TextField()),
                ('deadline', models.DateField()),
                ('responsible_party', models.CharField(help_text='Petitioner, Respondent, Registry, Police, Authority', max_length=150)),
                ('is_complied', models.BooleanField(default=False)),
                ('compliance_date', models.DateField(blank=True, null=True)),
                ('compliance_affidavit_filed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='orders_judgments.courtorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
