"""
companies_full_code - Aggregator Module
Preserves backward compatibility while keeping all underlying files < 250 KB
"""

from .companies_full_code_part01 import COMPANIES_IBC_SECTIONS_PART_01
from .companies_full_code_part02 import COMPANIES_IBC_SECTIONS_PART_02
from .companies_full_code_part03 import COMPANIES_IBC_SECTIONS_PART_03
from .companies_full_code_part04 import COMPANIES_IBC_SECTIONS_PART_04
from .companies_full_code_part05 import COMPANIES_IBC_SECTIONS_PART_05
from .companies_full_code_part06 import COMPANIES_IBC_SECTIONS_PART_06
from .companies_full_code_part07 import COMPANIES_IBC_SECTIONS_PART_07
from .companies_full_code_part08 import COMPANIES_IBC_SECTIONS_PART_08
from .companies_full_code_part09 import COMPANIES_IBC_SECTIONS_PART_09
from .companies_full_code_part10 import COMPANIES_IBC_SECTIONS_PART_10
from .companies_full_code_part11 import COMPANIES_IBC_SECTIONS_PART_11
from .companies_full_code_part12 import COMPANIES_IBC_SECTIONS_PART_12
from .companies_full_code_part13 import COMPANIES_IBC_SECTIONS_PART_13
from .companies_full_code_part14 import COMPANIES_IBC_SECTIONS_PART_14
from .companies_full_code_part15 import COMPANIES_IBC_SECTIONS_PART_15
from .companies_full_code_part16 import COMPANIES_IBC_SECTIONS_PART_16
from .companies_full_code_part17 import COMPANIES_IBC_SECTIONS_PART_17
from .companies_full_code_part18 import COMPANIES_IBC_SECTIONS_PART_18
from .companies_full_code_part19 import COMPANIES_IBC_SECTIONS_PART_19
from .companies_full_code_part20 import COMPANIES_IBC_SECTIONS_PART_20
from .companies_full_code_part21 import COMPANIES_IBC_SECTIONS_PART_21
from .companies_full_code_part22 import COMPANIES_IBC_SECTIONS_PART_22
from .companies_full_code_part23 import COMPANIES_IBC_SECTIONS_PART_23
from .companies_full_code_part24 import COMPANIES_IBC_SECTIONS_PART_24

COMPANIES_IBC_SECTIONS = COMPANIES_IBC_SECTIONS_PART_01 + COMPANIES_IBC_SECTIONS_PART_02 + COMPANIES_IBC_SECTIONS_PART_03 + COMPANIES_IBC_SECTIONS_PART_04 + COMPANIES_IBC_SECTIONS_PART_05 + COMPANIES_IBC_SECTIONS_PART_06 + COMPANIES_IBC_SECTIONS_PART_07 + COMPANIES_IBC_SECTIONS_PART_08 + COMPANIES_IBC_SECTIONS_PART_09 + COMPANIES_IBC_SECTIONS_PART_10 + COMPANIES_IBC_SECTIONS_PART_11 + COMPANIES_IBC_SECTIONS_PART_12 + COMPANIES_IBC_SECTIONS_PART_13 + COMPANIES_IBC_SECTIONS_PART_14 + COMPANIES_IBC_SECTIONS_PART_15 + COMPANIES_IBC_SECTIONS_PART_16 + COMPANIES_IBC_SECTIONS_PART_17 + COMPANIES_IBC_SECTIONS_PART_18 + COMPANIES_IBC_SECTIONS_PART_19 + COMPANIES_IBC_SECTIONS_PART_20 + COMPANIES_IBC_SECTIONS_PART_21 + COMPANIES_IBC_SECTIONS_PART_22 + COMPANIES_IBC_SECTIONS_PART_23 + COMPANIES_IBC_SECTIONS_PART_24

