"""
cpc_sections_orders - Aggregator Module
Preserves backward compatibility while keeping all underlying files < 250 KB
"""

from .cpc_sections_orders_part01 import CPC_SECTIONS_REGISTRY_PART_01
from .cpc_sections_orders_part02 import CPC_SECTIONS_REGISTRY_PART_02
from .cpc_sections_orders_part03 import CPC_SECTIONS_REGISTRY_PART_03
from .cpc_sections_orders_part04 import CPC_SECTIONS_REGISTRY_PART_04

from .cpc_sections_orders_part05 import CPC_ORDERS_EXHAUSTIVE_PART_05
from .cpc_sections_orders_part06 import CPC_ORDERS_EXHAUSTIVE_PART_06
from .cpc_sections_orders_part07 import CPC_ORDERS_EXHAUSTIVE_PART_07
from .cpc_sections_orders_part08 import CPC_ORDERS_EXHAUSTIVE_PART_08
from .cpc_sections_orders_part09 import CPC_ORDERS_EXHAUSTIVE_PART_09
from .cpc_sections_orders_part10 import CPC_ORDERS_EXHAUSTIVE_PART_10
from .cpc_sections_orders_part11 import CPC_ORDERS_EXHAUSTIVE_PART_11
from .cpc_sections_orders_part12 import CPC_ORDERS_EXHAUSTIVE_PART_12
from .cpc_sections_orders_part13 import CPC_ORDERS_EXHAUSTIVE_PART_13
from .cpc_sections_orders_part14 import CPC_ORDERS_EXHAUSTIVE_PART_14
from .cpc_sections_orders_part15 import CPC_ORDERS_EXHAUSTIVE_PART_15
from .cpc_sections_orders_part16 import CPC_ORDERS_EXHAUSTIVE_PART_16
from .cpc_sections_orders_part17 import CPC_ORDERS_EXHAUSTIVE_PART_17
from .cpc_sections_orders_part18 import CPC_ORDERS_EXHAUSTIVE_PART_18
from .cpc_sections_orders_part19 import CPC_ORDERS_EXHAUSTIVE_PART_19
from .cpc_sections_orders_part20 import CPC_ORDERS_EXHAUSTIVE_PART_20
from .cpc_sections_orders_part21 import CPC_ORDERS_EXHAUSTIVE_PART_21
from .cpc_sections_orders_part22 import CPC_ORDERS_EXHAUSTIVE_PART_22
from .cpc_sections_orders_part23 import CPC_ORDERS_EXHAUSTIVE_PART_23
from .cpc_sections_orders_part24 import CPC_ORDERS_EXHAUSTIVE_PART_24
from .cpc_sections_orders_part25 import CPC_ORDERS_EXHAUSTIVE_PART_25
from .cpc_sections_orders_part26 import CPC_ORDERS_EXHAUSTIVE_PART_26
from .cpc_sections_orders_part27 import CPC_ORDERS_EXHAUSTIVE_PART_27
from .cpc_sections_orders_part28 import CPC_ORDERS_EXHAUSTIVE_PART_28
from .cpc_sections_orders_part29 import CPC_ORDERS_EXHAUSTIVE_PART_29
from .cpc_sections_orders_part30 import CPC_ORDERS_EXHAUSTIVE_PART_30

CPC_SECTIONS_REGISTRY = CPC_SECTIONS_REGISTRY_PART_01 + CPC_SECTIONS_REGISTRY_PART_02 + CPC_SECTIONS_REGISTRY_PART_03 + CPC_SECTIONS_REGISTRY_PART_04

CPC_ORDERS_EXHAUSTIVE = CPC_ORDERS_EXHAUSTIVE_PART_05 + CPC_ORDERS_EXHAUSTIVE_PART_06 + CPC_ORDERS_EXHAUSTIVE_PART_07 + CPC_ORDERS_EXHAUSTIVE_PART_08 + CPC_ORDERS_EXHAUSTIVE_PART_09 + CPC_ORDERS_EXHAUSTIVE_PART_10 + CPC_ORDERS_EXHAUSTIVE_PART_11 + CPC_ORDERS_EXHAUSTIVE_PART_12 + CPC_ORDERS_EXHAUSTIVE_PART_13 + CPC_ORDERS_EXHAUSTIVE_PART_14 + CPC_ORDERS_EXHAUSTIVE_PART_15 + CPC_ORDERS_EXHAUSTIVE_PART_16 + CPC_ORDERS_EXHAUSTIVE_PART_17 + CPC_ORDERS_EXHAUSTIVE_PART_18 + CPC_ORDERS_EXHAUSTIVE_PART_19 + CPC_ORDERS_EXHAUSTIVE_PART_20 + CPC_ORDERS_EXHAUSTIVE_PART_21 + CPC_ORDERS_EXHAUSTIVE_PART_22 + CPC_ORDERS_EXHAUSTIVE_PART_23 + CPC_ORDERS_EXHAUSTIVE_PART_24 + CPC_ORDERS_EXHAUSTIVE_PART_25 + CPC_ORDERS_EXHAUSTIVE_PART_26 + CPC_ORDERS_EXHAUSTIVE_PART_27 + CPC_ORDERS_EXHAUSTIVE_PART_28 + CPC_ORDERS_EXHAUSTIVE_PART_29 + CPC_ORDERS_EXHAUSTIVE_PART_30

