"""
special_tribunals_code - Aggregator Module
Preserves backward compatibility while keeping all underlying files < 250 KB
"""

from .special_tribunals_code_part01 import TRIBUNAL_REGULATIONS_PART_01
from .special_tribunals_code_part02 import TRIBUNAL_REGULATIONS_PART_02
from .special_tribunals_code_part03 import TRIBUNAL_REGULATIONS_PART_03
from .special_tribunals_code_part04 import TRIBUNAL_REGULATIONS_PART_04
from .special_tribunals_code_part05 import TRIBUNAL_REGULATIONS_PART_05
from .special_tribunals_code_part06 import TRIBUNAL_REGULATIONS_PART_06
from .special_tribunals_code_part07 import TRIBUNAL_REGULATIONS_PART_07
from .special_tribunals_code_part08 import TRIBUNAL_REGULATIONS_PART_08
from .special_tribunals_code_part09 import TRIBUNAL_REGULATIONS_PART_09
from .special_tribunals_code_part10 import TRIBUNAL_REGULATIONS_PART_10
from .special_tribunals_code_part11 import TRIBUNAL_REGULATIONS_PART_11
from .special_tribunals_code_part12 import TRIBUNAL_REGULATIONS_PART_12
from .special_tribunals_code_part13 import TRIBUNAL_REGULATIONS_PART_13
from .special_tribunals_code_part14 import TRIBUNAL_REGULATIONS_PART_14
from .special_tribunals_code_part15 import TRIBUNAL_REGULATIONS_PART_15

TRIBUNAL_REGULATIONS = TRIBUNAL_REGULATIONS_PART_01 + TRIBUNAL_REGULATIONS_PART_02 + TRIBUNAL_REGULATIONS_PART_03 + TRIBUNAL_REGULATIONS_PART_04 + TRIBUNAL_REGULATIONS_PART_05 + TRIBUNAL_REGULATIONS_PART_06 + TRIBUNAL_REGULATIONS_PART_07 + TRIBUNAL_REGULATIONS_PART_08 + TRIBUNAL_REGULATIONS_PART_09 + TRIBUNAL_REGULATIONS_PART_10 + TRIBUNAL_REGULATIONS_PART_11 + TRIBUNAL_REGULATIONS_PART_12 + TRIBUNAL_REGULATIONS_PART_13 + TRIBUNAL_REGULATIONS_PART_14 + TRIBUNAL_REGULATIONS_PART_15

