# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CASE_CREATED', 'Case Created'), ('CASE_STATUS_CHANGED', 'Case Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('EVIDENCE_MUTATED', 'Evidence Modified'), ('ORDER_RECORDED', 'Court Order Recorded'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('SECURITY_ALERT', 'Security Violation Attempt')], db_index=True, max_length=50)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
