# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_active_cases', models.PositiveIntegerField(default=0)),
                ('total_disposed_cases', models.PositiveIntegerField(default=0)),
                ('total_hearings_held', models.PositiveIntegerField(default=0)),
                ('total_revenue_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_revenue_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('compliance_rate_percent', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
