# Generated by Django 5.0.6 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('CASE_ASSIGNED', 'New Case Assignment'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('HEARING_CHANGED', 'Hearing Rescheduled / Postponed'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('DEADLINE_OVERDUE', 'Deadline Overdue'), ('DOCUMENT_UPLOADED', 'New Document Uploaded'), ('TASK_ASSIGNED', 'Task Assigned'), ('ORDER_PASSED', 'Court Order Passed'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECEIVED', 'Payment Received')], default='CASE_ASSIGNED', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
